poliedro_donate/blueprints/donations.py
from poliedro_donate.database import commit_on_success

__all__ = ('donations_bp', 'donation')

from collections import OrderedDict
from werkzeug.exceptions import NotFound
from flask import Blueprint, render_template, redirect, url_for, make_response

from .. import strings, app
from ..auth import requires_auth
from ..database import helpers
from ..database.models import Donation, User, Transaction
from ..validator import LOCATIONS, STRETCH_GOAL_PRICES

import json

donations_bp = Blueprint('donations', __name__)


@donations_bp.route('/')
@requires_auth
def list_all():
    costs = 0
    d = Donation.query.all()

    total = 0
    fees = 0
    for donation in d:
        if donation.transaction.state == 'approved':
            total += donation.amount
            costs += app.config["APP_SG_COSTS"][donation.stretch_goal] * donation.items
            try:
              fees += float(json.loads(donation.transaction.result_obj)['transactions'][0]['related_resources'][0]['sale']['transaction_fee']['value'])
            except:
              pass

    remaining = total - costs - fees
    total, costs, fees, remaining = round(total, 2), round(costs, 2), round(fees, 2), round(remaining, 2)
    total, costs, fees, remaining = "{:0.2f}".format(total), "{:0.2f}".format(costs), "{:0.2f}".format(
        fees), "{:0.2f}".format(remaining),

    return render_template('donations/list_all.html', donations=d, total=total, costs=costs, fees=fees,
                           remaining=remaining)


@donations_bp.route('/D<int:d_id>T<int:t_id>')
@donations_bp.route('/D<int:d_id>T<int:t_id>/')
@requires_auth
def donation(d_id, t_id):
    d = Donation.query.filter_by(id=d_id, transaction_id=t_id).first_or_404()
    return render_template('donations/donation.html', donation=d, dbhelpers=helpers, strings=strings)


@donations_bp.route('/D<int:d_id>T<int:t_id>/approve')
@donations_bp.route('/D<int:d_id>T<int:t_id>/approve/')
@requires_auth
@commit_on_success
def donation_approve(d_id, t_id):
    t = Transaction.query.filter_by(id=t_id).first_or_404()
    t.state = "approved"
    t.payment_obj = '"Manually approved"'
    t.result_obj = '"Manually approved"'
    return redirect(url_for('donations.donation', d_id=d_id, t_id=t_id))


@donations_bp.route('/D<int:d_id>T<int:t_id>/disapprove')
@donations_bp.route('/D<int:d_id>T<int:t_id>/disapprove/')
@requires_auth
@commit_on_success
def donation_disapprove(d_id, t_id):
    t = Transaction.query.filter_by(id=t_id).first_or_404()
    t.state = "disapproved"
    t.payment_obj = '"Manually disapproved"'
    t.result_obj = '"Manually disapproved"'
    return redirect(url_for('donations.donation', d_id=d_id, t_id=t_id))


@donations_bp.route('/reference/<int:r_id>')
@donations_bp.route('/reference/<int:r_id>/')
@requires_auth
def reference(r_id):
    r = User.query.filter_by(id=r_id).first_or_404()
    return render_template('donations/reference.html', reference=r)


@donations_bp.route('/by_location/<location>')
@donations_bp.route('/by_location/<location>/')
@requires_auth
def by_location(location):
    if location not in LOCATIONS:
        raise NotFound()

    refs = User.query.filter_by(location=location).order_by(User.lastname).all()
    donation_sort_key = lambda d: d.id
    return render_template('donations/by_location.html', refs=refs, location=location,
                           donation_sort_key=donation_sort_key, dbhelpers=helpers, strings=strings, sum=sum)


@donations_bp.route('/by_location/<location>.md')
@requires_auth
def location_markdown(location):
    if location not in LOCATIONS:
        raise NotFound()

    d = Donation.query\
        .join(Donation.reference)\
        .filter(User.location == location)\
        .group_by(Donation)\
        .order_by(Donation.id)\
        .join(Donation.transaction)\
        .filter(Transaction.state == 'approved')\
        .group_by(Donation)\
        .all()
    resp = make_response(render_template('donations/by_location.md', donations=d, location=location))
    resp.headers['Content-type'] = 'text/plain; charset=utf-8'
    return resp


@donations_bp.route('/by_location/<location>/labels')
@donations_bp.route('/by_location/<location>/labels/')
@requires_auth
def print_labels(location):
    if location not in LOCATIONS:
        raise NotFound()

    refs = User.query.filter_by(location=location).order_by(User.lastname).all()
    donation_sort_key = lambda d: d.id
    return render_template('donations/print_labels.html', refs=refs, location=location,
                           donation_sort_key=donation_sort_key, dbhelpers=helpers, strings=strings)


@donations_bp.route('/to_order')
@donations_bp.route('/to_order/')
@requires_auth
def to_order():
    transactions = Transaction.query.filter_by(state='approved')
    shirts = []
    stretch_goals = [0] * len(STRETCH_GOAL_PRICES)

    for transaction in transactions:
        if transaction.donation.stretch_goal > 0:
            stretch_goals[transaction.donation.stretch_goal] += transaction.donation.items

        if transaction.donation.stretch_goal == 2:
            shirts += transaction.donation.shirts

    # Count gadgets for each stretch goal
    for i in range(len(stretch_goals)):
        stretch_goals[i] += sum(stretch_goals[i + 1:])

    return render_template('donations/to_order.html', stretch_goals=stretch_goals, shirts=shirts, dbhelpers=helpers,
                           strings=strings)

poliedro_donate/templates/donations/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>

        {% block style %}
            <style type="text/css">
                table {
                    width: 100%;
                    border-collapse: collapse;
                }

                table, th, td {
                    border: 1px solid black;
                }

                @media print {
                    .no-print {
                        display: none !important;
                    }

                    @page {
                        margin: 0;
                    }

                    body {
                        margin: 6mm;
                    }

                    a, a:active, a:visited, a:focus, a:hover {
                        color: black !important;
                        text-decoration: none !important;
                    }
                }

                .shirts-donation-row {
                    text-align: center;
                }

                .shirts-donation-row ul {
                    padding: 0;
                    margin: 5px;
                }

                .shirts-donation-row li {
                    display: inline-block;
                    padding: 5px;
                    border: 1px solid lightgray;
                }
            </style>
        {% endblock %}
    {% endblock %}
</head>
<body>
{% block nav %}
    <nav class="no-print">
        <a href="{{ url_for("donations.list_all") }}">All donations</a>
        &bullet;
        <a href="{{ url_for("donations.to_order") }}">Gadgets to order</a>
        &bullet;
        Gadgets by campus: <a href="{{ url_for("donations.by_location", location="leonardo") }}">Leonardo</a>, <a
            href="{{ url_for("donations.by_location", location="bovisa") }}">Bovisa</a>
    </nav>
{% endblock %}

{% block body %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

poliedro_donate/templates/donations/by_location.html
{% extends 'donations/base.html' %}

{% block title %}Gadgets for {{ location.capitalize() }} campus{% endblock %}

{% block style %}
    {{ super() }}

    <style type="text/css">
        tr.main-donation-row {
            border-top: 3px solid black;
        }
    </style>
{% endblock %}

{% block body %}
    {{ super() }}

    <h1>Gadgets for {{ location.capitalize() }} campus</h1>

    <p class="no-print">
        &xrArr; <a href="{{ url_for("donations.print_labels", location=location) }}">Print labels</a>
    </p>

    <div>
        <table>
            <thead>
            <tr>
                <th>Last name</th>
                <th>First name</th>
                <th>ID</th>
                <th>Stretch goal</th>
                <th>Items</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Amount</th>
            </tr>
            </thead>
            <tbody>
            {% for reference in refs %}
                {% for donation in sorted(reference.donations, key=donation_sort_key) %}
                    {% if donation.stretch_goal == 0 or not donation.transaction or donation.transaction.state != "approved" %}
                    {% else %}

                        <tr class="main-donation-row">
                            <td>
                                <a href="{{ url_for("donations.reference", r_id=reference.id) }}">{{ reference.lastname }}</a>
                            </td>
                            <td>{{ reference.firstname }}</td>
                            <td>
                                <a href="{{ url_for("donations.donation", d_id=donation.id, t_id=donation.transaction_id) }}">{{ donation.pretty_id }}</a>
                            </td>
                            <td>{{ donation.stretch_goal }}</td>
                            <td>{{ donation.items }}</td>
                            <td><a href="mailto:{{ reference.email }}">{{ reference.email }}</a></td>
                            <td><a href="tel:{{ reference.phone }}">{{ reference.phone }}</a></td>
                            <td>{{ donation.amount }}</td>
                        </tr>

                        {% if donation.stretch_goal == 2 %}
                            {% with shirts=dbhelpers.shirts_hr_count(donation.shirts) %}
                                <tr class="shirts-donation-row">
                                    {% for t, sizes in shirts.items() %}
                                        <td colspan="4">

                                            <div>{% if sum(sizes.values()) != 0 %}
                                                {{ strings.HR_SHIRT_TYPES['en'][t] }}{% endif %}</div>
                                            <div>
                                                <ul>
                                                    {% for s, count in sizes.items() %}
                                                        {% if count > 0 %}
                                                            <li>{{ count }} {{ s }}</li>
                                                        {% endif %}
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endwith %}
                        {% endif %}
                        {% if donation.notes %}
                            <tr class="shirts-donation-row">
                                <td colspan="1">
                                    <strong>Notes</strong>
                                </td>
                                <td colspan="7">
                                    {{ donation.notes }}
                                </td>
                            </tr>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}

poliedro_donate/templates/donations/donation.html
{% extends 'donations/base.html' %}

{% block title %}Donation {{ donation.pretty_id }}{% endblock %}

{% block body %}
    {{ super() }}

    <h1>Donation {{ donation.pretty_id }}</h1>

    <div>
        {% if donation.reference %}
            &xrArr; <a href="{{ url_for("donations.reference", r_id=donation.reference.id) }}">Reference</a>
        {% else %}
            <i>No reference</i>
        {% endif %}
    </div>

    <div>
        <ul>
            <li><strong>ID</strong>: {{ donation.pretty_id }}</li>
            <li><strong>Amount</strong>: &euro;{{ donation.amount }}</li>
            <li><strong>Stretch goal</strong>: {{ donation.stretch_goal }} -
                <i>{{ strings.STRETCH_GOAL_NAMES['en'][donation.stretch_goal] }}</i></li>
            <li><strong>Items</strong>: {{ donation.items }}</li>
            <li><strong>Notes</strong>: {{ donation.notes }}</li>
        </ul>
    </div>


    {% if donation.stretch_goal == 2 and donation.items > 0 %}
        <div>
            <h2>Shirts</h2>
            {% with lang='en' %}
                {% include 'shirts_table.html' %}
            {% endwith %}
        </div>
    {% endif %}


    {% if donation.transaction %}
        <div>
            <h2>Associated transaction</h2>
            <div>
                {% if donation.transaction.state != "approved" %}
                    <a href="{{ url_for("donations.donation_approve", d_id=donation.id, t_id=donation.transaction_id) }}">Mark as approved</a>
                {% else %}
                    <a href="{{ url_for("donations.donation_disapprove", d_id=donation.id, t_id=donation.transaction_id) }}">Mark as not approved</a>
                {% endif %}
            </div>
            <ul>
                <li><strong>Payment ID</strong>: {{ donation.transaction.payment_id }}</li>
                <li><strong>Payer ID</strong>: {{ donation.transaction.payer_id }}</li>
                <li><strong>State</strong>: {{ donation.transaction.state }}</li>
                {% if donation.transaction.payment_obj %}
                    <li><strong>Payment object</strong>: <br>
                        <pre>{{ json.dumps(json.loads(donation.transaction.payment_obj), indent=True) }}</pre>
                    </li>
                {% endif %}
                {% if donation.transaction.result_obj %}
                    <li><strong>Result object</strong>: <br>
                        <pre>{{ json.dumps(json.loads(donation.transaction.result_obj), indent=True) }}</pre>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}

{% endblock %}

poliedro_donate/templates/donations/list_all.html
{% extends 'donations/base.html' %}

{% block title %}All donations{% endblock %}

{% block body %}
    {{ super() }}

    <h1>All donations</h1>

    <p>{{ len(donations) }} donations - &euro;{{ total }} raised - &euro;{{ costs }} for paying gadgets - &euro;{{ fees }} PayPal fees - &euro;{{ remaining }} profit</p>

    <div>
        {% if len(donations) == 0 %}
            <i>Empty</i>
        {% else %}
            <table>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Reference</th>
                    <th>Amount</th>
                    <th>Stretch goal</th>
                    <th>Items</th>
                    <th>Trans. state</th>
                </tr>
                </thead>
                <tbody>
                {% for donation in donations %}
                    <tr>
                        <td>
                            <a href="{{ url_for("donations.donation", d_id=donation.id, t_id=donation.transaction_id) }}">{{ donation.pretty_id }}</a>
                        </td>
                        <td>
                            {% if donation.reference %}
                                <a href="{{ url_for("donations.reference", r_id=donation.user_id) }}">{{ donation.user_id }}
                                    ({{ donation.reference.firstname }} {{ donation.reference.lastname }})</a>
                            {% else %}
                                <i>None</i>
                            {% endif %}
                        </td>
                        <td>
                            &euro;{{ donation.amount }}
                        </td>
                        <td>
                            {{ donation.stretch_goal }}
                        </td>
                        <td>
                            {{ donation.items }}
                        </td>
                        <td>
                            {% if donation.transaction and donation.transaction.state %}
                                {{ donation.transaction.state }}
                            {% else %}
                                <i>n/a</i>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        {% endif %}
    </div>

{% endblock %}

poliedro_donate/templates/donations/print_labels.html
{% extends 'donations/base.html' %}

{% block title %}Labels for {{ location.capitalize() }} campus{% endblock %}

{% block style %}
    {{ super() }}

    <style type="text/css">
        main.labels {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(12cm, 1fr));
            grid-gap: 1mm;
        }

        .donation-label {
            display: flex;
            flex-flow: column;
            position: relative;
            width: 100%;
            border: 1px dashed black;
            padding: 0;
        }

        .donation-label .label-wrapper {
            padding: 3mm;
        }

        .donation-label h1 {
            margin: 0;
            font-size: 40pt;
            padding-left: 20px;
        }

        .donation-label ul {
            display: block;
            float: left;
            margin: 0;
        }

        .donation-label .int-border {
            position: absolute;
            border-left: 0.5px dashed black;
            height: 100%;
            width: 0;
            right: 25%;
            top: 0;
        }

        .larger {
            font-size: larger;
        }
    </style>
{% endblock %}

{% block body %}
    {{ super() }}


    <main class="labels">
        {% for reference in refs %}
            {% for donation in sorted(reference.donations, key=donation_sort_key) %}
                {% if donation.stretch_goal == 0 or not donation.transaction or donation.transaction.state != "approved" %}
                {% else %}

                    <div class="donation-label">
                        <div class="label-wrapper">
                            <h1>{{ donation.pretty_id[1:] }}</h1>
                            <ul>
                                <li><b><span class="larger">{{ donation.reference.lastname }}, {{ donation.reference.firstname }}</span></b></li>
                                <li>{{ donation.reference.email }}</li>
                                <li>{{ donation.reference.phone }}</li>
                            </ul>
                            <ul>
                                <li>Gadg: {{ donation.stretch_goal }}</li>
                                <li>Qty: {{ donation.items }}</li>
                                <li>Cmps: {{ location.capitalize()[:3] }}</li>
                            </ul>
                        </div>
                        <div class="int-border"></div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </main>

{% endblock %}

poliedro_donate/templates/donations/reference.html
{% extends 'donations/base.html' %}

{% block title %}Reference {{ reference.id }}{% endblock %}

{% block body %}
    {{ super() }}

    <h1>Reference {{ reference.id }}</h1>


    <div>
        <ul>
            <li><strong>First name</strong>: {{ reference.firstname }}</li>
            <li><strong>Last name</strong>: {{ reference.lastname }}</li>
            <li><strong>Email</strong>: <a href="mailto:{{ reference.email }}">{{ reference.email }}</a></li>
            <li><strong>Phone</strong>: <a href="tel:{{ reference.phone }}">{{ reference.phone }}</a></li>
            <li><strong>Location</strong>: {{ reference.location }}</li>
            <li><strong>Lang</strong>: {{ reference.lang }}</li>
        </ul>
    </div>

    <h2>Donations</h2>
    <ul>
        {% if len(reference.donations) == 0 %}
            <li><i>No donations.</i></li>
        {% else %}
            {% for d in reference.donations %}
                <li><a href="{{ url_for("donations.donation", d_id=d.id, t_id=d.transaction_id) }}">Donation {{ d.pretty_id }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>

{% endblock %}

poliedro_donate/templates/donations/to_order.html
{% extends 'donations/base.html' %}

{% block title %}Gadgets to order{% endblock %}

{% block body %}
    {{ super() }}

    <h1>Gadgets to order</h1>


    <div>

        {# Gadget names are hardcoded. This is not optimal. #}
        <ul>
            <li>Sackpacks: {{ stretch_goals[1] }}</li>
            <li>Pins: {{ stretch_goals[1] }}</li>
            <li>Rainbow Band: {{ stretch_goals[1] }}</li>
            <li>Puller: {{ stretch_goals[1] }}</li>
            <li>Shirts: {{ stretch_goals[2] }}</li>
        </ul>


        {% with shirts=dbhelpers.shirts_hr_count(shirts) %}
            <ul>
                {% for t, sizes in shirts.items() %}
                    <li>
                        {{ strings.HR_SHIRT_TYPES['en'][t] }}
                        <ul>
                            {% for s, count in sizes.items() %}
                                {% if count > 0 %}
                                    <li>{{ s }}: {{ count }}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endwith %}

    </div>

{% endblock %}